CC	= gcc 
TFLAGS  = -DDOS -mcpu=i686 -DC80x86 -O2 -fomit-frame-pointer 
RM	= del
B	= drivers/

all:		fest

OBJDRIVER	= ${B}cli.o ${B}sb.o
LDRIVER		= -lm

include Makefile.base

${B}cli.o:	${B}cli.c
include Makefile.common
